/**
* @file system.hpp
 * @brief The central simulation driver and state owner.
 *
 * The System class owns all simulation data (particles, container, forces,
 * boundaries, fields, controllers) and provides the main API for running
 * the simulation.
 *
 * It is constructed exclusively via the build_system() factory after the
 * declarative Environment has been "compiled".
 */

#pragma once

#include "april/core/environment.hpp"
#include "april/core/domain.hpp"
#include "april/containers/container.hpp"
#include "april/containers/batching/common.hpp"
#include "april/exec/policy.hpp"
#include "april/exec/particle_kernel.hpp"
#include "april/core/context.hpp"
#include "april/exec/executor.hpp"

namespace april {
	struct BuildInfo;

	template <class SystemConfig>
	class System;


	/**
	 * @brief Internal configuration bundle for System instantiation.
	 * * Stores all components (Container, Tables, Controllers) generated during
	 * the build phase. Components are stored as values to allow for zero-cost
	 * move-semantics into the final System object.
	 * * @tparam ParticleContainer The spatial layout backend (AoS, SoA, or AoSoA).
	 * @tparam EnvTraits Metadata derived from the Environment definition.
	 * @tparam ExecCfg The parallel and vectorization policies.
	 */
	template<
		class ParticleContainer,
		core::internal::IsEnvironmentTraits EnvTraits,
		exec::IsExecutionConfig ExecCfg>
	struct SystemConfig {
		using Container = ParticleContainer;
		using ExecutionConfig = ExecCfg;
		using BoundaryTable = EnvTraits::boundary_table_t;
		using InteractionTable = EnvTraits::force_table_t;
		using ParticleRecord = EnvTraits::particle_record_t;
		using ParticleAttributes = EnvTraits::particle_attributes_t;
		using Controllers = EnvTraits::controller_storage_t;
		using Fields = EnvTraits::field_storage_t;

		Container container; // Keep as value
		ExecutionConfig execution_config; // Keep as value
		std::vector<ParticleRecord> particles; // Change to value!
		BoundaryTable boundaries; // Change to value!
		InteractionTable interactions; // Change to value!
		Controllers controllers; // Change to value!
		Fields fields; // Change to value!
	};


	// forward declaration. see build.hpp
	template <class ContainerCfg, core::IsEnvironment Env, exec::IsExecutionConfig ExecCfg>
	requires container::IsContainerDecl<ContainerCfg, typename Env::traits, ExecCfg>
	auto build_system(
		const Env & environment,
		const ContainerCfg & container_config,
		const ExecCfg & execution_config,
		BuildInfo * build_info
	);



	/**
	 * @brief The main simulation driver.
	 * * The System coordinates the lifecycle of the simulation. It owns the memory
	 * and provides the API for running physics kernels, updating state, and
	 * querying particle data.
	 * * @tparam SystemConfig The configuration type generated by the factory.
	 */
	template <class SystemConfig>
	class System final {
		// --------------
		// INTERNAL TYPES
		// --------------
		using Controllers		= SystemConfig::Controllers;
		using Fields			= SystemConfig::Fields;
		using InteractionTable 	= SystemConfig::InteractionTable;
		using BoundaryTable  	= SystemConfig::BoundaryTable;
	public:
		// ----------------
		// PUBLIC API TYPES
		// ----------------
		using SysContext = core::SystemContext<System>;
		using TrigContext = utility::internal::TriggerContextImpl<System>;
		using ParticleAttributes= SystemConfig::ParticleAttributes;
		using ParticleRec		= SystemConfig::ParticleRecord;
		using Container			= SystemConfig::Container;
		using ExecutionConfig   = SystemConfig::ExecutionConfig;
		using ThreadExecutor	= ExecutionConfig::ThreadExecutor;

		/// @brief The global default parallelization policy for this system.
		static constexpr auto parallel_policy = ExecutionConfig::parallel_policy;
		/// @brief The global default vectorization policy for this system.
		static constexpr auto vector_policy = ExecutionConfig::vector_policy;

	private:
		// ---------------
		// PRIVATE MEMBERS
		// ---------------
		ThreadExecutor thread_executor;
		BoundaryTable boundary_table;
		InteractionTable force_table;
		Controllers controllers;
		Fields fields;
		Container particle_container;
		ExecutionConfig exec_config;

		// Buffers for parallel updates. Used to in apply_boundary_conditions
		struct alignas(64) PaddedThreadBuffer { std::vector<size_t> buffer; };
		std::vector<PaddedThreadBuffer> thread_update_buffers;
		std::vector<size_t> particles_to_update_buffer;

		double time_ = 0;
		size_t step_ = 0;

		core::SystemContext<System> system_context;
		utility::internal::TriggerContextImpl<System> trig_context;


		/// @brief Internal constructor used by build_system.
		explicit System(SystemConfig&& config)
		  : thread_executor(typename ExecutionConfig::ThreadExecutor(config.execution_config.executer_config)),
			boundary_table(std::move(config.boundaries)),
			force_table(std::move(config.interactions)),
			controllers(std::move(config.controllers)),
			fields(std::move(config.fields)),
			particle_container(std::move(config.container)),
			exec_config(std::move(config.execution_config)),
			system_context(*this),
			trig_context(*this)
		{
			particle_container.bind_executor(&thread_executor);
			particle_container.invoke_build(config.particles);
			controllers.for_each_item([&](auto& c) { c.dispatch_init(context()); });
			fields.for_each_item([&](auto& f) { f.dispatch_init(context()); });

			thread_update_buffers.resize(thread_executor.num_threads());
		}

		// only entry point for constructing a System (friend factory)
		template <class C, core::IsEnvironment E, exec::IsExecutionConfig EC>
	    requires container::IsContainerDecl<C, typename E::traits, EC>
	    friend auto build_system(const E&, const C&, const EC&, BuildInfo*);

		/// @brief Maps generic kernels to the container's Scalar/Vector batch paths.
		template<VectorPolicy V, container::batching::IsBatch Batch, exec::IsKernel Kernel>
		void execute_batch_kernel(const Batch& batch, Kernel&& kernel);
	public:
		// make non copyable
		System(const System&) = delete;
		System& operator=(const System&) = delete;
		System(System&&) = delete;
		System& operator=(System&&) = delete;

		// -----------------
		// LIFECYCLE & STATE
		// -----------------
		/** @brief Returns the current simulation time. */
		[[nodiscard]] double time() const noexcept { return time_; }

		/** @brief Returns the number of completed simulation steps. */
		[[nodiscard]] size_t step() const noexcept { return step_; }

		/** @brief Advances the simulation time by the given timestep. */
		void update_time(const double dt) noexcept { time_ += dt; }

		/** @brief Increments the step counter by one. */
		void increment_step() noexcept { ++step_; }

		/** @brief Resets time and step counter to zero. */
		void reset_time() noexcept { time_ = 0; step_ = 0; }

		/** @brief Returns the current simulation domain as a Box. */
		[[nodiscard]] core::Box box() const { return particle_container.simulation_domain(); }

		// TODO check if domain() is used anywhere and if it can be deleted
		[[nodiscard]] Domain domain() const { return
			{ particle_container.simulation_domain().min,  particle_container.simulation_domain().extent};
		}


		// ------------------
		// PARTICLE ACCESSORS
		// ------------------
		// "at" implies mutable access, "view" implies read-only,

		/**
		* @brief Access a particle by its physical index.
		* @note Indices are unstable and may change during rebuild_structure()
		* or any container sorting operations.
		* @tparam Read Fields to load into the accessor for reading.
		* @tparam Write Fields to allow modifications for.
		* @param index The current physical index of the particle in memory.
		* @return A ScalarParticleRef proxy.
		* @note The actual Write mask in the returned proxy will have
		* ParticleField::id removed to prevent accidental ID corruption.
		*/
		template<ParticleField Read, ParticleField Write = Read>
		[[nodiscard]] auto at(const size_t index) {
			// return type: ScalarParticleRef
			return particle_container.template at<Read, Write>(index);
		}

		/**
		* @brief Access a particle by its physical index (Read-Only).
		* @tparam Read Fields to load into the view.
		* @param index The current physical index of the particle.
		* @return A read-only ScalarParticleRef (View).
		*/
		template<ParticleField Read>
		[[nodiscard]] auto view(const size_t index) const {
			return particle_container.template view<Read>(index);
		}

		/**
		* @brief Access a particle by its persistent ID.
		* @note Slower than index-based access due to internal lookup,
		* but remains valid across structure rebuilds and particle migrations.
		* @tparam Read Fields to load into the accessor.
		* @tparam Write Fields to allow modifications for.
		* @param id The unique identifier of the particle.
		* @return A ScalarParticleRef proxy.
		* @note The actual Write mask in the returned proxy will have
		* ParticleField::id removed to prevent accidental ID corruption.
		*/
		template<ParticleField Read, ParticleField Write = Read>
		[[nodiscard]] auto at_id(const ParticleID id) {
			// type: particle::internal::ScalarParticleRef<Read, Write, ParticleData>
			return particle_container.template at_id<Read, Write>(id);
		}

		/**
		* @brief Access a particle by its persistent ID (Read-Only).
		* @tparam Read Fields to load into the view.
		* @param id The unique identifier of the particle.
		* @return A read-only ScalarParticleRef (View).
		*/
		template<ParticleField Read>
		[[nodiscard]]auto view_id(const ParticleID id) const {
			// type: particle::internal::ScalarParticleRef<Read, ParticleField::none, ParticleData>
			return particle_container.template view_id<Read>(id);
		}


		// -----------
		// ID INDEXING
		// -----------
		/// @brief Returns the minimum particle ID present in the system.
		[[nodiscard]] ParticleID min_id() const noexcept{
			return particle_container.min_id();
		}

		/// @brief Returns the maximum particle ID present in the system.
		[[nodiscard]] ParticleID max_id() const noexcept {
			return particle_container.max_id();
		}

		/// @brief Checks if a specific particle ID exists in the simulation.
		[[nodiscard]] bool contains_id(const ParticleID id) const noexcept {
			// with min_id anc max_id can write a stable for loop:
			//	for (auto id = min_id(); id < max_id; id++) { if !contains_id(id) continue; ...}
			return particle_container.invoke_contains_id(id);
		}

		/// @brief Resolves an ID to its current physical memory index.
		[[nodiscard]] size_t id_to_index(const ParticleID id) const noexcept {
			return particle_container.invoke_id_to_index(id);
		}


		// -------
		// QUERIES
		// -------
		// number of particles

		/**
		* @brief Returns the number of particles in the simulation.
		* @param state A bitmask to filter particles by their current state
		* (e.g., ALIVE, STATIONARY). Defaults to ALL.
		* @return The total count of particles matching the state criteria.
		* @note The current implementation returns the total particle count
		* regardless of the state parameter. Proper state-filtering is planned.
		*/
		[[nodiscard]] size_t size(const ParticleState = ParticleState::ALL) const noexcept {
			// TODO implement this method (system::size) properly
			return particle_container.invoke_particle_count();
		}

		/**
		* @brief Retrieves the physical indices of all particles within a spatial region.
		* @param region A Domain object defining the search area.
		* @return A vector of current physical indices for particles within the domain.
		* @note This is a convenience wrapper for the Box-based query_region.
		* @warning The returned indices are unstable and should be used immediately.
		*/
		[[nodiscard]] std::vector<size_t> query_region(const core::Box & region) const {
			return particle_container.invoke_collect_indices_in_region(region);
		}
		/**
		* @brief Retrieves the physical indices of all particles within a spatial region.
		* @param region A Domain object defining the search area.
		* @return A vector of current physical indices for particles within the domain.
		* @note This is a convenience wrapper for the Box-based query_region.
		* @warning The returned indices are unstable and should be used immediately.
		*/
		[[nodiscard]] std::vector<size_t> query_region(const Domain & region) const {
			return query_region(core::Box(region.min_corner().value(), region.max_corner().value()));
		}


		// ---------------------
		// ITERATION & REDUCTION
		// ---------------------
		/**
		* @brief Primary loop for per-particle operations.
		* * Used for operations that act on individual particles in isolation, such
		* as integrators (updating position/velocity) or property initializers.
		* * @tparam P ParallelPolicy (e.g., Threaded, Serial).
		* @tparam V VectorPolicy (e.g., Auto, Scalar, Vector).
		* @tparam Kernel A kernel wrapped via scalar_kernel, vector_kernel, or universal_kernel.
		* @param func The kernel implementation to execute.
		* @param state A bitmask filter to skip particles not in the specified state.
		*/
		template<
			ParallelPolicy P=ParallelPolicy::Serial,
			VectorPolicy V=vector_policy,
			exec::IsKernel Kernel>
		void for_each_particle(Kernel && func, ParticleState state = ParticleState::ALL) {
			particle_container.template for_each_particle<P, V, Kernel>(std::forward<Kernel>(func), state);
		}

		/**
		* @brief Read-only version of for_each_particle.
		* * Enforces at compile-time that the provided kernel does not attempt
		* to write to any particle fields.
		* * @tparam P ParallelPolicy (e.g., Threaded, Serial).
		* @tparam V VectorPolicy (e.g., Auto, Scalar, Vector).
		* @tparam Kernel A kernel wrapped via scalar_kernel, vector_kernel, or universal_kernel.
		* @param func The kernel implementation to execute.
		* * @note Triggers a static_assert if Kernel::Write is not ParticleField::none.
		*/
		template<
			ParallelPolicy P=ParallelPolicy::Serial,
			VectorPolicy V=vector_policy,
			exec::IsKernel Kernel>
		void for_each_particle_view(Kernel && func, ParticleState state = ParticleState::ALL) const {
			static_assert(std::remove_cvref_t<Kernel>::Write == ParticleField::none,
				"[APRIL] System: Kernel in for_each_particle_view must not have "
				"mutable fields (Kernel::Write must equal ParticleField::none"
			);
			particle_container.template for_each_particle<P, V, Kernel>(std::forward<Kernel>(func), state);
		}

		/**
		* @brief Performs a parallel map-reduce operation over the particle set.
		* * @tparam M The ParticleField mask required by the Mapper.
		* @tparam T The return type of the reduction.
		* @param initial_value The starting value for the reduction (e.g., 0.0).
		* @param map_func A lambda: (ParticleAccessor) -> T.
		* @param reduce_func A binary associative operator: (T, T) -> T. Defaults to std::plus.
		* @param state State filter mask.
		* @return The final reduced value.
		* @note Current implementation is a functional fallback; optimized
		* container-specific paths are WIP.
		*/
		// TODO actually implement on container level
		template<ParticleField M, typename Mapper, typename T, typename Reducer = std::plus<T>>
		[[nodiscard]] T reduce(
			T initial_value,
			Mapper&& map_func, // map particle -> T
			Reducer&& reduce_func = {},
			ParticleState state = ParticleState::ALIVE
		) const {
			return particle_container.invoke_iterate_state(initial_value, map_func, reduce_func, state);
		}


		/**
		* @brief Low-level batch iteration for custom interaction logic.
		* * Provides direct access to compute batches and the Boundary Condition
		* Provider (BCP). This is a "power-user" API for implementing
		* non-standard multi-body interactions or custom neighbor-list logic.
		* * @param func A lambda with signature: (Batch, BCP).
		*/
		template<ParallelPolicy P=ParallelPolicy::Serial, typename Func>
		void for_each_interaction_batch(Func && func) { // func signature: func(batch, bcp)
			particle_container.template invoke_for_each_interaction_batch<P>(std::forward<Func>(func));
		}

		/**
		* @brief High-level pairwise interaction loop.
		* * The standard way to implement N-Body or short-range forces.
		* * LOGIC:
		* 1. Iterates through all scheduled interaction batches.
		* 2. Uses a "Bridge" to calculate the distance vector 'r' between particles.
		* 3. Applies the BCP (Boundary Condition Provider) to 'r' to handle periodicity.
		* 4. Dispatches to the appropriate SIMD or Scalar kernel path.
		* * @tparam Kernel A kernel accepting (p1, p2, r).
		* @param func The interaction kernel.
		* @note If the kernel signature only accepts (p1, p2), 'r' calculation is skipped.
		* @warning Requires ParticleField::position in the Kernel::Read mask if 'r' is used.
		*/
		template<exec::IsKernel Kernel>
		void for_each_interaction_pair(Kernel && func) { // func(particle, particle, dist)
			auto update_batch = [&]<container::batching::IsBCP BCP>(const container::batching::IsBatch auto& batch, BCP && apply_bcp) {
				using K = std::remove_cvref_t<Kernel>;

				auto bridge = [&](auto&& p1, auto&& p2) {
					// If it doesn't accept 2 arguments, assume it requires the distance vector (3 arguments)
					constexpr bool takes_2_args = std::is_invocable_v<K, decltype(p1), decltype(p2)>;
					constexpr bool requires_r = !takes_2_args;

					constexpr bool position_requested = particle::internal::has_field_v<K::Read, ParticleField::position>;

					if constexpr (requires_r && position_requested) {
						auto diff = p2.position - p1.position;

						const auto r = [&] {
							if constexpr (std::is_same_v<std::remove_cvref_t<BCP>, container::batching::NoBatchBCP>) {
								return diff;
							} else {
								return apply_bcp(diff);
							}
						}();

						func(p1, p2, r);
					} else if constexpr (requires_r && !position_requested) {
						static_assert(false,
							"[APRIL] ERROR: Kernel requires distance vector 'r', but ParticleField::position is missing from the ReadMask.");
					} else {
						func(p1, p2); // Fallback to 2-argument invocation
					}
				};

				auto kernel = exec::internal::KernelWrapper<K::Read, K::Write, K::Mode, decltype(bridge)>{bridge};
				execute_batch_kernel<vector_policy>(batch, kernel);
			};

			for_each_interaction_batch(update_batch);
		}



		// -----------------
		// STRUCTURE UPDATES
		// -----------------
		/**
		* @brief Triggers a full rebuild of the container's spatial data structures.
		* * This updates Linked Cells, Verlet lists, or sorting based on the
		* current particle positions. It must be called periodically to ensure
		* particles remain in the correct interaction bins.
		*/
		void rebuild_structure() {
			particle_container.invoke_rebuild_structure();
		}

		/**
		* @brief Notifies the container that specific particles have moved.
		* * @param indices A list of physical indices for particles that moved.
		* @note Depending on the container implementation, this may perform
		* a lightweight local update or trigger a full rebuild.
		*/
		void notify_moved(const std::vector<size_t> & indices) {
			particle_container.invoke_notify_moved(indices);
		}

		/**
		* @brief Notifies the container that specific particles have moved (by ID).
		* * @param ids A list of persistent IDs for particles that moved.
		* @note Resolves IDs to indices before notifying the container.
		*/
		void notify_moved_id(const std::vector<ParticleID> & ids) {
			std::vector<size_t> indices;
			indices.reserve(ids.size());

			for (auto id : ids) {
				indices.push_back(particle_container.invoke_id_to_index(id));
			}

			particle_container.invoke_notify_moved(indices);
		}


		// -------
		// PHYSICS
		// -------
		// NOTE: These methods define the default simulation loop stages. In
		// future versions, these will be abstracted into composable "Compute Stages."

		/**
		 * @brief Orchestrates the calculation of all pairwise interactions.
		 * * Coordinates force reset, batch dispatch, and Reciprocal (N3L) updates
		 * for both type-based and ID-based (topological) forces.
		 */
		void update_forces();

		/**
		 * @brief Detects and handles particles interacting with domain boundaries.
		 * * This includes applying periodic shifts, reflective forces, or
		 * deletions (Open boundaries).
		 */
		void apply_boundary_conditions();

		/**
		 * @brief Executes all registered Controllers.
		 * * Controllers are triggered based on time or step conditions and
		 * typically handle thermostats, barostats, or custom logging.
		 */
		void apply_controllers();

		/**
		 * @brief Applies forces from global Fields (Gravity, Electric fields, etc.).
		 * * Fields are applied to every particle matching the field's Read mask,
		 * typically in a single parallel pass.
		 */
		void apply_force_fields();

		/**
		 * @brief Triggers internal update logic for all system components.
		 * * Allows Fields and Controllers to update their own internal state
		 * (e.g. ramping field strength) at the end of a time step.
		 */
		void update_all_components();


		// --------
		// CONTEXTS
		// --------
		/**
		* @brief Access the standard SystemContext.
		* * Provides a restricted, stable API for components that need to
		* read or modify the system state (e.g. Controllers).
		*/
		[[nodiscard]] SysContext & context() {
			return system_context;
		}

		/**
		 * @brief Access the TriggerContext.
		 * * Specialized context for evaluating conditional triggers based on
		 * time, steps, or physical events.
		 */
		[[nodiscard]] TrigContext & trigger_context() {
			return trig_context;
		}

		[[nodiscard]] const SysContext & context() const {
			return system_context;
		}
		[[nodiscard]] const TrigContext & trigger_context() const {
			return trig_context;
		}
	};


	namespace core {
		namespace internal {
			template<typename>
			inline constexpr bool is_system_v = false;

			// mark all System<C, Env, ExecCfg> instantiations as true (template specialization
			template<class Container, IsEnvironmentTraits EnvTraits, exec::IsExecutionConfig ExecCfg>
			inline constexpr bool is_system_v<System<SystemConfig<Container, EnvTraits, ExecCfg>>> = true;
		}

		template<typename T>
		concept IsSystem = internal::is_system_v<std::remove_cvref_t<T>>;
	}

} // namespace april::core

#include "april/core/internal/system_impl.hpp"

