/**
* @file system.hpp
 * @brief Defines APRIL's central simulation state owner and execution interface.
 *
 * The System class owns the simulation's particle container, interactions,
 * boundaries, controllers, fields, execution resources, and lifecycle state.
 *
 * System instances are created through build_system() after a declarative
 * Environment has been converted into concrete runtime components.
 */
#pragma once

#include <cstddef>
#include <functional>
#include <type_traits>
#include <utility>
#include <vector>

#include "april/core/environment.hpp"
#include "april/core/domain.hpp"
#include "april/containers/container.hpp"
#include "april/containers/batching/batch.hpp"
#include "april/exec/policy.hpp"
#include "april/exec/kernel.hpp"
#include "april/core/context.hpp"

namespace april {
	struct BuildInfo;
	template <class SystemConfig> class System;


	namespace core::internal {

		/**
		 * @internal
		 * @brief Fully assembled component bundle used to construct a System.
		 *
		 * Stores the container, interaction table, controllers, fields, execution
		 * configuration, and initial particle records produced during the build phase.
		 *
		 * Components are stored by value so they can be moved directly into the final
		 * System instance.
		 *
		 * @tparam ParticleContainer Concrete particle-storage and traversal backend.
		 * @tparam EnvTraits Traits generated from the declarative Environment.
		 * @tparam ExecCfg Execution policies and thread-executor configuration.
		 */
		template<
			class ParticleContainer,
			IsEnvironmentTraits EnvTraits,
			exec::IsExecutionConfig ExecCfg>
		struct SystemBuildConfig {
			using Container = ParticleContainer;
			using ExecutionConfig = ExecCfg;
			using BoundaryTable = EnvTraits::boundary_table_t;
			using InteractionTable = EnvTraits::force_table_t;
			using ParticleRecord = EnvTraits::particle_record_t;
			using ParticleAttributes = EnvTraits::particle_attributes_t;
			using Controllers = EnvTraits::controller_storage_t;
			using Fields = EnvTraits::field_storage_t;

			Container container;
			ExecutionConfig execution_config;
			std::vector<ParticleRecord> particles;
			BoundaryTable boundaries;
			InteractionTable interactions;
			Controllers controllers;
			Fields fields;
		};
	}


	/// forward declaration. see build.hpp
	template <class ContainerCfg, core::IsEnvironment Env, exec::IsExecutionConfig ExecCfg>
	requires container::IsContainerDecl<ContainerCfg, typename Env::traits, ExecCfg>
	auto build_system(
		const Env & environment,
		const ContainerCfg & container_config,
		const ExecCfg & execution_config,
		BuildInfo * build_info
	);



	/**
	 * @brief Owns and coordinates a complete APRIL simulation.
	 *
	 * System owns the particle container, execution resources, interaction tables,
	 * boundaries, controllers, fields, and simulation lifecycle state.
	 *
	 * System instances cannot be constructed directly. They are created exclusively
	 * through build_system(), which validates the declarative Environment and
	 * assembles the concrete runtime configuration.
	 *
	 * System is non-copyable and non-movable because its context objects store
	 * references to the owning System instance, and the particle container is bound
	 * to execution resources owned by that same instance. Moving the object would
	 * invalidate those internal relationships.
	 *
	 * @tparam SystemConfig Fully assembled configuration generated by build_system().
	 */
	template <class SystemConfig>
	class System final {
		// --------------
		// INTERNAL TYPES
		// --------------
		using Controllers		= SystemConfig::Controllers;
		using Fields			= SystemConfig::Fields;
		using InteractionTable 	= SystemConfig::InteractionTable;
		using BoundaryTable  	= SystemConfig::BoundaryTable;
	public:
		// ----------------
		// PUBLIC API TYPES
		// ----------------
		using SystemContext = core::SystemContext<System>;
		using TriggerContext = utility::internal::TriggerContextImpl<System>;
		using ParticleAttributes= SystemConfig::ParticleAttributes;
		using ParticleRec		= SystemConfig::ParticleRecord;
		using Container			= SystemConfig::Container;
		using ExecutionConfig   = SystemConfig::ExecutionConfig;
		using ThreadExecutor	= ExecutionConfig::ThreadExecutor;

		/// Default parallel policy configured for internal system operations.
		static constexpr auto parallel_policy = ExecutionConfig::parallel_policy;
		/// Default vectorization policy used by particle and interaction kernels.
		static constexpr auto vector_policy = ExecutionConfig::vector_policy;

		// Context objects retain references to this instance.
		System(const System&) = delete;
		System& operator=(const System&) = delete;
		System(System&&) = delete;
		System& operator=(System&&) = delete;

		// -----------------
		// LIFECYCLE & STATE
		// -----------------
		/// Returns the current simulation time.
		[[nodiscard]] double time() const noexcept { return time_; }

		/// Returns the number of completed simulation steps.
		[[nodiscard]] size_t step() const noexcept { return step_; }

		/// Advances the simulation time by the given timestep.
		void update_time(const double dt) noexcept { time_ += dt; }

		/// Increments the step counter by one.
		void increment_step() noexcept { ++step_; }

		/// Resets the time and step counter to zero.
		void reset_time() noexcept { time_ = 0; step_ = 0; }

		/// Returns the current simulation domain as a Box.
		[[nodiscard]] core::Box box() const {
			return particle_container.simulation_domain();
		}

		/// Returns the current simulation domain as a Domain (min point and extent).
		[[nodiscard]] Domain domain() const {
			return {
				particle_container.simulation_domain().min,
				particle_container.simulation_domain().extent
			 };
		}

		// ------------------
		// PARTICLE ACCESSORS
		// ------------------
		// "at" implies mutable access, "view" implies read-only,

		/**
		 * @brief Accesses a particle by its current storage index.
		 *
		 * @tparam Read Particle fields exposed for reading.
		 * @tparam Write Particle fields exposed for modification. Defaults to Read.
		 *
		 * @param index Current physical index of the particle in the container.
		 *
		 * @return A mutable scalar particle proxy (ScalarParticleRef) exposing the requested fields.
		 *
		 * @warning Physical indices may change after container rebuilds, sorting, or
		 * other structural updates. Do not retain an index across such operations.
		 *
		 * @note ParticleField::id may be removed from the effective write mask to
		 * prevent accidental modification of persistent particle identifiers.
		 */
		template<ParticleField Read, ParticleField Write = Read>
		[[nodiscard]] auto at(const size_t index) {
			// return type: ScalarParticleRef
			return particle_container.template at<Read, Write>(index);
		}

		/**
		 * @brief Obtains read-only access to a particle by storage index.
		 *
		 * @tparam Read Particle fields exposed for reading.
		 *
		 * @param index Current physical index of the particle in the container.
		 *
		 * @return A read-only scalar particle proxy (ScalarParticleRef) exposing the requested fields.
		 *
		 * @warning Physical indices may change after container rebuilds, sorting, or
		 * other structural updates. Do not retain an index across such operations.
		 */
		template<ParticleField Read>
		[[nodiscard]] auto view(const size_t index) const {
			return particle_container.template view<Read>(index);
		}

		/**
		 * @brief Accesses a particle by its persistent identifier.
		 *
		 * @tparam Read Particle fields exposed for reading.
		 * @tparam Write Particle fields exposed for modification. Defaults to Read.
		 *
		 * @param id Persistent particle identifier.
		 *
		 * @return A mutable scalar particle proxy (ScalarParticleRef) exposing the requested fields.
		 *
		 * @throws Depending on the configured assertion policy, invalid identifiers may
		 * trigger an assertion or container-specific failure.
		 *
		 * @note ID-based access may require an identifier-to-index lookup and can be
		 * slower than direct index access.
		 *
		 * @note ParticleField::id may be removed from the effective write mask.
		 */
		template<ParticleField Read, ParticleField Write = Read>
		[[nodiscard]] auto at_id(const ParticleID id) {
			return particle_container.template at_id<Read, Write>(id);
		}

		/**
		 * @brief Obtains read-only access to a particle by its persistent identifier.
		 *
		 * @tparam Read Particle fields exposed for reading.
		 *
		 * @param id Persistent particle identifier.
		 *
		 * @return A mutable scalar particle proxy (ScalarParticleRef) exposing the requested fields.
		 *
		 * @throws Depending on the configured assertion policy, invalid identifiers may
		 * trigger an assertion or container-specific failure.
		 *
		 * @note ID-based access may require an identifier-to-index lookup and can be
		 * slower than direct index access.
		 */
		template<ParticleField Read>
		[[nodiscard]]particle::internal::ScalarParticleRef<Read, ParticleField::none, ParticleAttributes>
		view_id(const ParticleID id) const {
			return particle_container.template view_id<Read>(id);
		}


		// -----------
		// ID INDEXING
		// -----------
		/// Returns the smallest particle identifier currently present.
		[[nodiscard]] ParticleID min_id() const noexcept {
			return particle_container.invoke_min_id();
		}

		/// Returns the largest particle identifier currently present.
		[[nodiscard]] ParticleID max_id() const noexcept {
			return particle_container.invoke_max_id();
		}

		/**
		 * @brief Checks whether a particle identifier currently exists.
		 *
		 * @param id Particle identifier to test.
		 * @return true if the identifier belongs to a current particle; otherwise false.
		 *
		 * @note Particle IDs are generally dense. A stable ID-based traversal can be
		 * written by iterating from min_id() through max_id() and skipping IDs for
		 * which contains_id() returns false.
		 */
		[[nodiscard]] bool contains_id(const ParticleID id) const noexcept {
			return particle_container.invoke_contains_id(id);
		}

		/**
		 * @brief Resolves a persistent particle identifier to its current storage index.
		 *
		 * @param id Particle identifier to resolve.
		 * @return Current physical index of the particle.
		 *
		 * @warning The returned index may become invalid after a structural update.
		 */
		[[nodiscard]] size_t id_to_index(ParticleID id) const noexcept {
			return particle_container.invoke_id_to_index(id);
		}


		// -------
		// QUERIES
		// -------

		/**
		 * @brief Returns the number of particles matching a state mask.
		 *
		 * @param state Particle-state mask to count.
		 * @return Number of matching particles.
		 *
		 * @note The current implementation ignores state and returns the total particle
		 * count.
		 */
		[[nodiscard]] size_t size(const ParticleState state  = ParticleState::ALL) const noexcept {
			// TODO implement this method (system::size) properly
			(void)state;
			return particle_container.invoke_particle_count();
		}

		/**
		 * @brief Returns the current indices of particles inside a spatial region.
		 *
		 * @param region Axis-aligned region to query.
		 * @return Physical indices of particles contained in the region.
		 *
		 * @warning Returned indices may become invalid after structural updates.
		 */
		[[nodiscard]] std::vector<size_t> query_region(const core::Box & region) const {
			return particle_container.invoke_collect_indices_in_region(region);
		}
		/**
		 * @brief Returns the current indices of particles inside a domain.
		 *
		 * @param region Domain to query.
		 * @return Physical indices of particles contained in the domain.
		 *
		 * @warning Returned indices may become invalid after structural updates.
		 */
		[[nodiscard]] std::vector<size_t> query_region(const Domain & region) const {
			return query_region(
				core::Box(
					region.min_corner().value(),
					region.max_corner().value()
				)
			);
		}


		// ---------------------
		// ITERATION & REDUCTION
		// ---------------------
		/**
		 * @brief Applies a kernel to each particle matching a state mask.
		 *
		 * The kernel may accept either `(particle)` or `(index, particle)`.
		 *
		 * Execution is serial by default because APRIL does not assume that the kernel
		 * or its captured state is safe for concurrent invocation. Select a parallel
		 * policy explicitly only when the complete kernel operation is thread-safe.
		 *
		 * @tparam P Parallel execution policy.
		 * @tparam V Vectorization policy used to select supported execution paths.
		 * @tparam Kernel APRIL kernel type describing read permissions, write
		 * permissions, and supported execution modes.
		 *
		 * @param func Kernel invoked for every matching particle.
		 * @param state Particle-state mask used to filter the iteration.
		 */
		template<
			ParallelPolicy P=ParallelPolicy::Serial,
			VectorPolicy V=vector_policy,
			exec::IsKernel Kernel>
		void for_each_particle(Kernel && func, ParticleState state = ParticleState::ALL) {
			// TODO add early stopping for search kernels (kernels that return bool)
			particle_container.template for_each_particle<P, V>(
				std::forward<Kernel>(func),
				state
			);
		}

		/**
		 * @brief Applies a read-only kernel to each particle matching a state mask.
		 *
		 * The kernel may accept either `(particle)` or `(index, particle)`.
		 *
		 * Execution is serial by default because read-only particle access does not
		 * guarantee that the kernel's captured state is thread-safe.
		 *
		 * @tparam P Parallel execution policy.
		 * @tparam V Vectorization policy used to select supported execution paths.
		 * @tparam Kernel APRIL kernel type whose write mask must be
		 * ParticleField::none.
		 *
		 * @param func Read-only kernel invoked for every matching particle.
		 * @param state Particle-state mask used to filter the iteration.
		 */
		template<
			ParallelPolicy P=ParallelPolicy::Serial,
			VectorPolicy V=vector_policy,
			exec::IsKernel Kernel>
		void for_each_particle_view(Kernel && func, ParticleState state = ParticleState::ALL) const {
			static_assert(std::remove_cvref_t<Kernel>::Write == ParticleField::none,
				"[APRIL] System: Kernel in for_each_particle_view must not have "
				"mutable fields (Kernel::Write must equal ParticleField::none"
			);
			particle_container.template for_each_particle<P, V, Kernel>(
				std::forward<Kernel>(func),
				state
			);
		}

		/**
		 * @brief Maps matching particles to values and reduces them into one result.
		 *
		 * The mapper is invoked once for every particle matching `state`. The generic
		 * fallback executes serially, although containers may provide a specialized
		 * implementation.
		 *
		 * @tparam M Particle fields exposed to the mapper.
		 * @tparam Mapper Callable with a signature equivalent to `T mapper(particle)`.
		 * @tparam T Reduction value type.
		 * @tparam Reducer Callable with a signature equivalent to `T reducer(T accumulated, T value)`.
		 *
		 * @param initial_value Initial accumulator value.
		 * @param map_func Callable that maps a particle accessor to a value of type T.
		 * @param reduce_func Callable that combines the current accumulator with one
		 * mapped value and returns the updated accumulator.
		 * @param state Particle-state mask used to select particles.
		 *
		 * @return Final accumulated value after all matching particles have been mapped
		 * and reduced.
		 */
		template<ParticleField M, typename Mapper, typename T, typename Reducer = std::plus<T>>
		[[nodiscard]] T reduce(
			T initial_value,
			Mapper&& map_func, // map particle -> T
			Reducer&& reduce_func = {},
			ParticleState state = ParticleState::ALIVE
		) const {
			// TODO actually implement on container level
			return particle_container.template invoke_reduce<M>(
				initial_value,
				std::forward<Mapper>(map_func),
				std::forward<Reducer>(reduce_func),
				state
			);
		}


		/**
		 * @brief Applies a callback to each scheduled interaction batch.
		 *
		 * This is a low-level API intended for custom interaction dispatch and
		 * container-specific batch processing.
		 *
		 * Execution is serial by default because the callback and captured state are
		 * not assumed to be thread-safe.
		 *
		 * @tparam P Parallel execution policy used while traversing batches.
		 * @tparam Func Callable accepting the concrete batch and its boundary-condition
		 * provider.
		 *
		 * @param func Callback invoked for each interaction batch.
		 */
		template<ParallelPolicy P=ParallelPolicy::Serial, typename Func>
		void for_each_interaction_batch(Func && func) {
			particle_container.template invoke_for_each_interaction_batch<P>(std::forward<Func>(func));
		}

		/**
		 * @brief Applies a kernel to each scheduled particle pair.
		 *
		 * Kernels accepting `(p1, p2)` are invoked without calculating a displacement.
		 * Kernels accepting `(p1, p2, r)` additionally receive the boundary-adjusted
		 * displacement from the first particle to the second.
		 *
		 * @tparam Kernel APRIL kernel type describing particle-field access and
		 * supported execution modes.
		 *
		 * @param func Pair kernel invoked for each scheduled interaction.
		 *
		 * @note Kernels accepting `r` must include ParticleField::position in their
		 * read mask.
		 */
		template<exec::IsKernel Kernel>
		void for_each_interaction_pair(Kernel && func) { // func(particle, particle, dist)
			auto update_batch = [&]<container::batching::IsBCP BCP>(const container::batching::IsBatch auto& batch, BCP && apply_bcp) {
				using K = std::remove_cvref_t<Kernel>;

				auto bridge = [&](auto&& p1, auto&& p2) {
					// If it doesn't accept 2 arguments, assume it requires the distance vector (3 arguments)
					constexpr bool takes_2_args = requires { func(p1, p2); };
					constexpr bool requires_r = !takes_2_args;

					constexpr bool position_requested = particle::internal::has_field_v<K::Read, ParticleField::position>;

					if constexpr (requires_r && position_requested) {
						auto diff = p2.position - p1.position;

						const auto r = [&] {
							// NoBatchBCP represents an interaction path requiring no boundary adjustment.
							if constexpr (std::is_same_v<std::remove_cvref_t<BCP>, container::batching::NoBatchBCP>) {
								return diff;
							} else {
								return apply_bcp(diff);
							}
						}();

						func(p1, p2, r);
					} else if constexpr (requires_r && !position_requested) {
						static_assert(false,
							"[APRIL] ERROR: Kernel requires distance vector 'r', but ParticleField::position is missing from the ReadMask.");
					} else {
						func(p1, p2); // Fallback to 2-argument invocation
					}
				};

				auto kernel = exec::make_kernel_wrapper<K>(std::move(bridge));
				execute_batch_kernel<vector_policy>(batch, kernel);
			};

			for_each_interaction_batch(update_batch);
		}



		// -----------------
		// STRUCTURE UPDATES
		// -----------------
		/**
		 * @brief Rebuilds the container's spatial and indexing structures.
		 *
		 * This may reorder particle storage and invalidate previously obtained physical
		 * indices and index-based accessors.
		 */
		void rebuild_structure() {
			particle_container.invoke_rebuild_structure();
		}

		/**
		 * @brief Notifies the container that particles with the given identifiers moved.
		 *
		 * Each identifier is resolved to its current physical index before the
		 * container is notified.
		 *
		 * @param ids Persistent identifiers of moved particles.
		 */
		void notify_moved_id(const std::vector<ParticleID> & ids) {
			std::vector<size_t> indices;
			indices.reserve(ids.size());

			for (auto id : ids) {
				indices.push_back(particle_container.invoke_id_to_index(id));
			}

			particle_container.invoke_notify_moved(indices);
		}

		/**
		 * @brief Notifies the container that particles at the given indices moved.
		 *
		 * The container may update its structures incrementally or fall back to a full
		 * rebuild.
		 *
		 * @param indices Current physical indices of moved particles.
		 *
		 * @warning The indices must refer to the current container layout.
		 */
		void notify_moved(const std::vector<size_t> & indices) {
			particle_container.invoke_notify_moved(indices);
		}


		// -------
		// PHYSICS
		// -------
		// NOTE: These methods define the default simulation loop stages. In
		// future versions, these will be abstracted into composable "Compute Stages."

		/**
		 * @brief Recomputes particle forces from configured pair and topology interactions.
		 *
		 * Existing force accumulators are reset before registered interactions are
		 * evaluated.
		 */
		void update_forces();

		/**
		 * @brief Applies all configured boundary conditions to affected particles.
		 *
		 * Boundary handlers may modify particle state, position, velocity, force, or
		 * removal status depending on their configured behavior.
		 */
		void apply_boundary_conditions();

		/**
		 * @brief Executes controllers whose trigger conditions are currently satisfied.
		 */
		void apply_controllers();

		/**
		 * @brief Applies all configured global force fields.
		 */
		void apply_force_fields();

		/**
		 * @brief Updates the internal state of registered controllers and fields.
		 *
		 * This allows stateful components to advance schedules, ramps, cached values,
		 * and other per-step state.
		 */
		void update_all_components();


		// --------
		// CONTEXTS
		// --------
		/**
		 * @brief Returns the restricted system interface used by simulation components.
		 *
		 * @return Mutable reference to the system context owned by this System.
		 */
		[[nodiscard]] SystemContext & context() {
			return system_context;
		}

		/**
		 * @brief Returns the trigger-evaluation context.
		 *
		 * @return Mutable reference to the trigger context owned by this System.
		 */
		[[nodiscard]] TriggerContext & trigger_context() {
			return trig_context;
		}

		/**
		 * @brief Returns a const restricted system interface used by simulation components.
		 *
		 * @return Const reference to the system context owned by this System.
		 */
		[[nodiscard]] const SystemContext& context() const noexcept {
			return system_context;
		}

		/**
		 * @brief Returns a const trigger-evaluation context.
		 *
		 * @return Const reference to the trigger context owned by this System.
		 */
		[[nodiscard]] const TriggerContext & trigger_context() const noexcept {
			return trig_context;
		}

	private:
		// ---------------
		// PRIVATE MEMBERS
		// ---------------
		ThreadExecutor thread_executor;
		BoundaryTable boundary_table;
		InteractionTable force_table;
		Controllers controllers;
		Fields fields;
		Container particle_container;
		ExecutionConfig exec_config;

		// Per-thread and merged buffers used while applying boundary conditions.
		// Separates thread-local vectors onto distinct cache lines to reduce false sharing.
		struct alignas(exec::assumed_cache_line_size) PaddedThreadBuffer {
			std::vector<size_t> buffer;
		};

		std::vector<PaddedThreadBuffer> thread_update_buffers;
		std::vector<size_t> particles_to_update_buffer;

		double time_ = 0;
		size_t step_ = 0;

		core::SystemContext<System> system_context;
		utility::internal::TriggerContextImpl<System> trig_context;


		/// @brief Internal constructor used by build_system.
		explicit System(SystemConfig&& config)
		  : thread_executor(config.execution_config.executor_config),
			boundary_table(std::move(config.boundaries)),
			force_table(std::move(config.interactions)),
			controllers(std::move(config.controllers)),
			fields(std::move(config.fields)),
			particle_container(std::move(config.container)),
			exec_config(std::move(config.execution_config)),
			system_context(*this),
			trig_context(*this)
		{
			particle_container.bind_executor(&thread_executor);
			particle_container.invoke_build(config.particles);

			thread_update_buffers.resize(thread_executor.num_threads());

			controllers.for_each_item([&](auto& controller) {
				controller.dispatch_init(context());
			});

			fields.for_each_item([&](auto& field) {
				field.dispatch_init(context());
			});
		}

		// build_system() is the only public construction path.
		template <class C, core::IsEnvironment E, exec::IsExecutionConfig EC>
	    requires container::IsContainerDecl<C, typename E::traits, EC>
	    friend auto build_system(const E&, const C&, const EC&, BuildInfo*);

		/// @brief Maps generic kernels to the container's Scalar/Vector batch paths.
		template<VectorPolicy V, container::batching::IsBatch Batch, exec::IsKernel Kernel>
		void execute_batch_kernel(const Batch& batch, Kernel&& kernel);
	};


	namespace core {
		namespace internal {
			template<typename>
			inline constexpr bool is_system_v = false;

			// Recognize System instantiations produced from APRIL's generated config.
			template<class Container, IsEnvironmentTraits EnvTraits, exec::IsExecutionConfig ExecCfg>
			inline constexpr bool is_system_v<System<SystemBuildConfig<Container, EnvTraits, ExecCfg>>> = true;
		}

		template<typename T>
		concept IsSystem = internal::is_system_v<std::remove_cvref_t<T>>;
	}

} // namespace april

#include "april/core/internal/system_impl.hpp"

